fix(sbom): conversion of CycloneDX SBOM with top-level annotations to SPDX failed
When converting a CycloneDX SBOM that had top-level annotations (currently
only information about which backend found specific packages), the
conversion failed. The cause was treating non-JSON values as JSON and
assuming that all package annotations were dictionaries.

This was most noticeable when merging SPDX and CycloneDX SBOMs.

│   729 │   │   for package in self.packages:
│   730 │   │   │   properties = [
│   731 │   │   │   │   (
│ ❱ 732 │   │   │   │   │   Property(**json.loads(an.comment))
│   733 │   │   │   │   │   if an.annotator.endswith(":jsonencoded")
│   734 │   │   │   │   │   else Property(name=an.annotator, value=an.comment)
│   735 │   │   │   │   )
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Signed-off-by: Jakub Nekvinda <jnekvind@redhat.com>